### ISSUE TITLE
sidebar and modal bootstrap

### ISSUE THREAD

**Issue by triteniun** [LynnHaDo/Personal-Website#1]
hello, first of all thank you for your work.
I'm using the menu for a personal work but I have a little problem. I can't use in the menu configuration with a bootstrap modal to open an image:

                    sidebar: {
                        collapsed: {
                            use: '(min-width: 450px)',
                            //hideNavbar: false,
                        },
                        expanded: {
                            //use: '(min-width: 992px)',
							
                        },
                    },

The image does not finish opening.
I tried it directly in the /demo/advanced.html file.
Is there any solution, thanks and greetings

**Comment by LynnHaDo** [comment]
Hi @triteniun,

Thank you for finding my project helpful. If I'm getting it right, are you mentioning the project-list-clicking animation on my portfolio website? If you look at the `frontend/src/app/components/project-list` folder, specifically the HTML, TS and CSS files, I created 3 different divs: the "opener", the blurry background, and the sidebar. I added a clicking event listener to the opener so that once clicked, the blurry background appears along with the sidebar. You can take a look at the CSS file for the sliding animation. 

Hope this helps!
